version: "3.8"

services:
  api:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./app/.env
    volumes:
      - ./playbooks:/playbooks

  worker:
    build: ./app
    command: celery -A worker.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - ./app/.env
    volumes:
      - ./playbooks:/playbooks

  redis:
    image: redis:7
    ports:
      - "6379:6379"
